import Head from 'next/head'
import Main from '../components/Home/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>KidsGallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main></Main>

    </div>
  )
}